/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'lazy-image.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./lazy-image.android-arm64.node')
          } else {
            nativeBinding = require('@alberteinshutoin/lazy-image-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'lazy-image.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./lazy-image.android-arm-eabi.node')
          } else {
            nativeBinding = require('@alberteinshutoin/lazy-image-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'lazy-image.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./lazy-image.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@alberteinshutoin/lazy-image-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'lazy-image.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./lazy-image.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@alberteinshutoin/lazy-image-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'lazy-image.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./lazy-image.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@alberteinshutoin/lazy-image-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'lazy-image.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./lazy-image.darwin-universal.node')
      } else {
        nativeBinding = require('@alberteinshutoin/lazy-image-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'lazy-image.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./lazy-image.darwin-x64.node')
          } else {
            nativeBinding = require('@alberteinshutoin/lazy-image-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'lazy-image.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./lazy-image.darwin-arm64.node')
          } else {
            nativeBinding = require('@alberteinshutoin/lazy-image-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'lazy-image.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./lazy-image.freebsd-x64.node')
      } else {
        nativeBinding = require('@alberteinshutoin/lazy-image-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'lazy-image.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./lazy-image.linux-x64-musl.node')
            } else {
              nativeBinding = require('@alberteinshutoin/lazy-image-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'lazy-image.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./lazy-image.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@alberteinshutoin/lazy-image-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'lazy-image.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./lazy-image.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@alberteinshutoin/lazy-image-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'lazy-image.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./lazy-image.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@alberteinshutoin/lazy-image-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'lazy-image.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./lazy-image.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@alberteinshutoin/lazy-image-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'lazy-image.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./lazy-image.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@alberteinshutoin/lazy-image-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'lazy-image.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./lazy-image.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@alberteinshutoin/lazy-image-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'lazy-image.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./lazy-image.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@alberteinshutoin/lazy-image-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'lazy-image.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./lazy-image.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@alberteinshutoin/lazy-image-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { ImageEngine, ErrorCategory, inspect, inspectFile, version, supportedInputFormats, supportedOutputFormats } = nativeBinding

/**
 * Extract error category from a lazy-image error
 * 
 * Errors from lazy-image include category information in the error.code property
 * (e.g., "LAZY_IMAGE_USER_ERROR") or error.category property (ErrorCategory enum value).
 * This helper extracts the category from these properties.
 * 
 * @param {Error} error - The error object from lazy-image
 * @returns {ErrorCategory|null} - The error category, or null if not found
 * 
 * @example
 * try {
 *   await engine.toBuffer('jpeg', 80)
 * } catch (err) {
 *   const category = getErrorCategory(err)
 *   if (category === ErrorCategory.UserError) {
 *     // Handle user input error
 *   } else if (category === ErrorCategory.CodecError) {
 *     // Handle codec/format error
 *   }
 * }
 */
function getErrorCategory(error) {
  if (!error) {
    return null
  }
  
  // First, try error.category (if set by create_napi_error_with_code)
  if (typeof error.category === 'number') {
    // ErrorCategory enum value (0=UserError, 1=CodecError, 2=ResourceLimit, 3=InternalBug)
    if (error.category >= 0 && error.category <= 3) {
      return error.category
    }
  }
  
  // Second, try error.code (standard pattern, like sharp uses)
  if (error.code) {
    switch (error.code) {
      case 'LAZY_IMAGE_USER_ERROR':
        return ErrorCategory.UserError
      case 'LAZY_IMAGE_CODEC_ERROR':
        return ErrorCategory.CodecError
      case 'LAZY_IMAGE_RESOURCE_LIMIT':
        return ErrorCategory.ResourceLimit
      case 'LAZY_IMAGE_INTERNAL_BUG':
        return ErrorCategory.InternalBug
      default:
        // Fall through to message parsing
    }
  }
  
  // Fall back to error.message parsing (for backward compatibility)
  // Note: This is a temporary fallback. New errors should use error.code or error.category.
  // Format 1: "CategoryName:Error message" (e.g., "UserError:Unsupported rotation angle...")
  // Format 2: "CODE:CategoryName:OriginalMessage" (e.g., "LAZY_IMAGE_USER_ERROR:UserError:Unsupported rotation angle...")
  if (error.message) {
    // Try format 2 first (CODE:CategoryName:OriginalMessage)
    // Extract code from the beginning, category name, and preserve the original message
    const codeMatch = error.message.match(/^(LAZY_IMAGE_\w+):(\w+):(.+)$/)
    if (codeMatch) {
      const code = codeMatch[1]
      switch (code) {
        case 'LAZY_IMAGE_USER_ERROR':
          return ErrorCategory.UserError
        case 'LAZY_IMAGE_CODEC_ERROR':
          return ErrorCategory.CodecError
        case 'LAZY_IMAGE_RESOURCE_LIMIT':
          return ErrorCategory.ResourceLimit
        case 'LAZY_IMAGE_INTERNAL_BUG':
          return ErrorCategory.InternalBug
        default:
          return null
      }
    }
    
    // Try format 1 (CategoryName:Error message)
    const categoryMatch = error.message.match(/^(UserError|CodecError|ResourceLimit|InternalBug):/)
    if (categoryMatch) {
      const categoryName = categoryMatch[1]
      switch (categoryName) {
        case 'UserError':
          return ErrorCategory.UserError
        case 'CodecError':
          return ErrorCategory.CodecError
        case 'ResourceLimit':
          return ErrorCategory.ResourceLimit
        case 'InternalBug':
          return ErrorCategory.InternalBug
        default:
          return null
      }
    }
  }
  
  return null
}

module.exports.ImageEngine = ImageEngine
module.exports.ErrorCategory = ErrorCategory
module.exports.getErrorCategory = getErrorCategory
module.exports.inspect = inspect
module.exports.inspectFile = inspectFile
module.exports.version = version
module.exports.supportedInputFormats = supportedInputFormats
module.exports.supportedOutputFormats = supportedOutputFormats
