/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

type CanonicalInputFormat = 'jpeg' | 'jpg' | 'png' | 'webp'
type CanonicalOutputFormat = CanonicalInputFormat | 'avif'
type CanonicalDeprecatedColorSpace = 'srgb'
type CanonicalPresetName = 'thumbnail' | 'avatar' | 'hero' | 'social'

export type CaseInsensitive<T extends string> =
  | T
  | Uppercase<T>
  | Lowercase<T>
  | Capitalize<T>
  | Uncapitalize<T>

export type InputFormat = CanonicalInputFormat
export type OutputFormat = CanonicalOutputFormat
export type DeprecatedColorSpace = CanonicalDeprecatedColorSpace
export type PresetName = CanonicalPresetName

export type OutputFormatInput = CaseInsensitive<CanonicalOutputFormat>
export type DeprecatedColorSpaceInput = CaseInsensitive<CanonicalDeprecatedColorSpace>
export type PresetNameInput = CaseInsensitive<CanonicalPresetName>

export interface Dimensions {
  width: number
  height: number
}
/** Result of applying a preset, contains recommended output settings */
export interface PresetResult {
  /** Recommended output format */
  format: OutputFormat
  /** Recommended quality (None for PNG) */
  quality?: number
  /** Target width (None if aspect ratio preserved) */
  width?: number
  /** Target height (None if aspect ratio preserved) */
  height?: number
}
export interface BatchResult {
  source: string
  success: boolean
  error?: string
  outputPath?: string
}
/** Image metadata returned by inspect() */
export interface ImageMetadata {
  /** Image width in pixels */
  width: number
  /** Image height in pixels */
  height: number
  /** Detected format (jpeg, png, webp, gif, etc.) */
  format?: string
}
/**
 * Inspect image metadata WITHOUT decoding pixels.
 * This reads only the header bytes - extremely fast (<1ms).
 *
 * Use this to check dimensions before processing, or to reject
 * images that are too large without wasting CPU on decoding.
 */
export declare function inspect(buffer: Buffer): ImageMetadata
/**
 * Inspect image metadata from a file path WITHOUT loading into Node.js heap.
 * **Memory-efficient**: Reads directly from filesystem, bypassing V8 entirely.
 * This is the recommended way for server-side metadata inspection.
 */
export declare function inspectFile(path: string): ImageMetadata
/** Get library version */
export declare function version(): string
/** Get supported input formats */
export declare function supportedInputFormats(): Array<InputFormat>
/** Get supported output formats */
export declare function supportedOutputFormats(): Array<OutputFormat>
/** Processing metrics for performance monitoring */
export interface ProcessingMetrics {
  /** Time taken to decode the image (milliseconds) */
  decodeTime: number
  /** Time taken to apply all operations (milliseconds) */
  processTime: number
  /** Time taken to encode the image (milliseconds) */
  encodeTime: number
  /** Peak memory usage during processing (bytes, as u32 for NAPI compatibility) */
  memoryPeak: number
}
export interface OutputWithMetrics {
  data: Buffer
  metrics: ProcessingMetrics
}
/**
 * The main image processing engine.
 *
 * Usage:
 * ```js
 * const result = await ImageEngine.from(buffer)
 *   .resize(800)
 *   .rotate(90)
 *   .grayscale()
 *   .toBuffer('jpeg', 75);
 * ```
 */
export declare class ImageEngine {
  /**
   * Create engine from a buffer. Decoding is lazy.
   * Extracts ICC profile from the source image if present.
   */
  static from(buffer: Buffer): ImageEngine
  /**
   * Create engine from a file path.
   * **TRUE LAZY LOADING**: Only stores the path - file is NOT read until needed.
   * This is the recommended way for server-side processing of large images.
   */
  static fromPath(path: string): ImageEngine
  /** Create a clone of this engine (for multi-output scenarios) */
  clone(): ImageEngine
  /** Resize image. Width or height can be null to maintain aspect ratio. */
  resize(width?: number | undefined | null, height?: number | undefined | null): ImageEngine
  /** Crop a region from the image. */
  crop(x: number, y: number, width: number, height: number): ImageEngine
  /** Rotate by degrees (90, 180, 270 only) */
  rotate(degrees: number): ImageEngine
  /** Flip horizontally */
  flipH(): ImageEngine
  /** Flip vertically */
  flipV(): ImageEngine
  /** Convert to grayscale */
  grayscale(): ImageEngine
  /**
   * Preserve metadata (Exif, ICC profile, XMP) in output.
   * By default, all metadata is stripped for security (no GPS leak) and smaller file sizes.
   * Call this method to keep metadata for photography sites or when color accuracy is important.
   */
  keepMetadata(): ImageEngine
  /** Adjust brightness (-100 to 100) */
  brightness(value: number): ImageEngine
  /** Adjust contrast (-100 to 100) */
  contrast(value: number): ImageEngine
  /**
   * Ensure the image is in RGB/RGBA format (pixel format conversion, not color space transformation)
   * Note: This does NOT perform ICC color profile conversion - it only ensures the pixel format.
   * For true color space conversion with ICC profiles, use a dedicated color management library.
   */
  ensureRgb(): ImageEngine
  /**
   * Legacy method - use ensureRgb() instead
   *
   * **Deprecated**: This method is deprecated and will be removed in v1.0.
   * Use `ensureRgb()` for pixel format conversion instead.
   *
   * Note: This method does NOT perform true color space conversion with ICC profiles.
   * It only ensures the pixel format is RGB/RGBA.
   */
  toColorspace(colorSpace: DeprecatedColorSpaceInput): ImageEngine
  /**
   * Apply a built-in preset for common use cases.
   *
   * Available presets:
   * - "thumbnail": 150x150, WebP quality 75 (gallery thumbnails)
   * - "avatar": 200x200, WebP quality 80 (profile pictures)
   * - "hero": 1920 width, JPEG quality 85 (hero images, banners)
   * - "social": 1200x630, JPEG quality 80 (OGP/Twitter cards)
   *
   * Returns the preset configuration for use with toBuffer/toFile.
   */
  preset(name: PresetNameInput): PresetResult
  /**
   * Encode to buffer asynchronously.
   * format: "jpeg", "jpg", "png", "webp", "avif"
   * quality: 1-100 (default 80, ignored for PNG)
   *
   * **Non-destructive**: This method can be called multiple times on the same engine instance.
   * The source data is cloned internally, allowing multiple format outputs.
   */
  toBuffer(format: OutputFormatInput, quality?: number | undefined | null): Promise<Buffer>
  /**
   * Encode to buffer asynchronously with performance metrics.
   * Returns `{ data: Buffer, metrics: ProcessingMetrics }`.
   *
   * **Non-destructive**: This method can be called multiple times on the same engine instance.
   * The source data is cloned internally, allowing multiple format outputs.
   */
  toBufferWithMetrics(format: OutputFormatInput, quality?: number | undefined | null): Promise<OutputWithMetrics>
  /**
   * Encode and write directly to a file asynchronously.
   * **Memory-efficient**: Combined with fromPath(), this enables
   * full file-to-file processing without touching Node.js heap.
   *
   * **Non-destructive**: This method can be called multiple times on the same engine instance.
   * The source data is cloned internally, allowing multiple format outputs.
   *
   * Returns the number of bytes written.
   */
  toFile(path: string, format: OutputFormatInput, quality?: number | undefined | null): Promise<number>
  /**
   * Get image dimensions WITHOUT full decoding.
   * For file paths, reads only the header bytes (extremely fast).
   * For in-memory buffers, uses header-only parsing.
   */
  dimensions(): Dimensions
  /**
   * Check if an ICC color profile was extracted from the source image.
   * Returns the profile size in bytes, or null if no profile exists.
   */
  hasIccProfile(): number | null
  /**
   * Process multiple images in parallel with the same operations.
   *
   * - inputs: Array of input file paths
   * - output_dir: Directory to write processed images
   * - format: Output format ("jpeg", "png", "webp", "avif")
   * - quality: Optional quality (1-100, uses format-specific default if None)
   * - concurrency: Optional number of parallel workers (default: CPU core count)
   */
  processBatch(inputs: Array<string>, outputDir: string, format: OutputFormatInput, quality?: number | undefined | null, concurrency?: number | undefined | null): Promise<BatchResult[]>
}
